### ISSUE TITLE
Do research on Backend tools.

### ISSUE THREAD

**Issue by Kielbasa21** [UB-CSE/course-project-codeville#11]

**Comment by Kielbasa21** [comment]
https://docs.google.com/document/d/1ZNi3SMIX_htkUWczokbO_n2QBmpjIbZtsU1IhuXrxMY/edit?usp=sharing

I am conflicted between cask and scalatra, I'm thinking more cask. I really like the organization of the documentation which you can find here: https://www.lihaoyi.com/cask/

For scalatra theres more overlay on their site: https://scalatra.org/getting-started/

**Comment by Jason-15** [comment]
[https://app.zenhub.com/files/293908949/d1c49871-72ee-4fd5-a3c3-1a38bfd926a0/download](https://app.zenhub.com/files/293908949/d1c49871-72ee-4fd5-a3c3-1a38bfd926a0/download)
