### ISSUE TITLE
Research on front-end technologies

### ISSUE THREAD

**Issue by prakharpbuf** [UB-CSE/course-project-codeville#12]

**Comment by prakharpbuf** [comment]
https://docs.google.com/document/d/18b2aZv3-iV3KNhKdMc3hcKRS6zcFsn998h-OCobvYYs/edit

Settled for vanilla languages: HTML5, CSS3, and JS

**Comment by Jason-15** [comment]
[https://app.zenhub.com/files/293908949/741c0b08-c424-44e3-9bf8-ef5f3d82a664/download](https://app.zenhub.com/files/293908949/741c0b08-c424-44e3-9bf8-ef5f3d82a664/download)
