### ISSUE TITLE
Create a prototype for the landing page

### ISSUE THREAD

**Issue by Manantiw** [UB-CSE/course-project-codeville#13]
Task Test:
1) Click on the Attached Images for both Desktop and Mobile view.
2) The Landing Page images should appear.
3) Check the details on the Landing Page.
4) There will be buttons for Login and Sign-up
5) View the Design of the Page.

**Comment by Manantiw** [comment]
[https://app.zenhub.com/files/293908949/aa458b9b-d07b-40b7-96a8-ae81c4ddc264/download](https://app.zenhub.com/files/293908949/aa458b9b-d07b-40b7-96a8-ae81c4ddc264/download)

[https://www.figma.com/proto/95vozzdWjdqjsF8HApDKx6/Untitled?node-id=2%3A2&scaling=scale-down](url)

**Comment by Jason-15** [comment]
Task Test:
1) Click on the Attached Image.
2) The Landing Page should appear.
3) Check the details on the Landing Page.
4) View the Design of the Page.
