### ISSUE TITLE
As a student who has registered for this webservice, I would like to have to land on a Homepage so that I can see which of my friends are taking the same courses as me

### ISSUE THREAD

**Issue by Jason-15** [UB-CSE/course-project-codeville#147]

**Comment by prakharpbuf** [comment]
1. go to /signup
2. signup using correct credentials
3. verify you account
4. login using correct credentials
5. enter personal details, educational details, and courses
6. you'll be redirected to homepage
7. Here, you should see a list of all courses you added on step 5
