### ISSUE TITLE
Create a prototype for an "About us" Page

### ISSUE THREAD

**Issue by Kielbasa21** [UB-CSE/course-project-codeville#20]
Page should describe what our service is, and what it provides.

Task Test:
1) Click on the Attached Image.
2) The "About Us" page should appear.
3) View About us information and its design
4) Have 2 buttons for logging in and signing up.
5) See placeholder images

**Comment by Jason-15** [comment]
Task Test:
1) Click on the attached document
2) The "About Us" page should appear
3) Read About us details

**Comment by Kielbasa21** [comment]
![AboutUs.png](https://images.zenhubusercontent.com/5f5938157f30fa6204d93d50/23b0eff4-093a-410e-88ab-f4da52f463aa)![AboutUsMobile.png](https://images.zenhubusercontent.com/5f5938157f30fa6204d93d50/6410625e-1af4-4c07-9333-4d11a7732bcd)

**Comment by Kielbasa21** [comment]
![Frame 2.png](https://images.zenhubusercontent.com/5f5938157f30fa6204d93d50/eef8ca09-7923-47f8-8419-8f6c1bca951b)
![Frame 8.png](https://images.zenhubusercontent.com/5f5938157f30fa6204d93d50/39289dc9-461a-467b-b62b-ddd6734056d5)
