### ISSUE TITLE
Create a prototype of login page

### ISSUE THREAD

**Issue by prakharpbuf** [UB-CSE/course-project-codeville#22]
Task Test:
1) Click on the attached Image/ Link for both desktop view and mobile view.
2) The "Login Page" should appear for both views.
3) Look through the Login page design.
4)There will be a space for username and password.
5) There will be a button for Logging in.
6) There will be a button for University at Buffalo Sign in.
7) There will be a link for "Forgot Password".
8) There will be a link for Signing up if no account exists .

**Comment by Jason-15** [comment]
Task Test:
1) Click on the attached document
2) The "Login Page" should appear
3) Look through the Login page design
4)There will be a space for username and password
5) There will be a button for Logging in

**Comment by prakharpbuf** [comment]
![loginmobile.png](https://images.zenhubusercontent.com/5f57de9f6f5ffa67c9431c95/02c40252-b355-4ed5-93fc-c64a9e9752eb)![login.png](https://images.zenhubusercontent.com/5f57de9f6f5ffa67c9431c95/88d92900-e3a4-4454-92dc-995333f4fa3b)
