### ISSUE TITLE
Create a prototype for the Sign up Page 

### ISSUE THREAD

**Issue by Manantiw** [UB-CSE/course-project-codeville#24]
Task Test:
1) Click on the Attached Images for both Desktop and mobile view[Desktop is wider, mobile is narrower].
2) The Signup Page Prototype should appear.
3) There should be a space entering Email, Password, Confirm Password.
4) There is a button to Begin(sign up).
5) There will also be a button for sign-up and Home.
6) View the Design

**Comment by Jason-15** [comment]
Task Test:
1) Click on the Attached file.
2) The Signup Page Prototype should appear.
3) There should be a space entering personal details.
4) Personal Details include First name, Last name, Email Address, and Password.
5) View the Design of the Prototype.

**Comment by Manantiw** [comment]
![Frame 5.png](https://images.zenhubusercontent.com/5f5938137a1b77c2b6023335/0fa8cddd-5595-4fa0-8076-74f067009c66)
