### ISSUE TITLE
As a student, I want to see the prototype of this web-service so that I can get the look and feel of it before it launches.

### ISSUE THREAD

**Issue by Jason-15** [UB-CSE/course-project-codeville#26]
Acceptance Test :

Click on the attached file
The prototype of the website should appear
See the look of the website

**Comment by manavsz** [comment]
Acceptance Test :

1. Click on the attached file
2. The prototype of the website should appear
3. See the look of the website

**Comment by manavsz** [comment]
**Prototype of the website**
[https://app.zenhub.com/files/293908949/0957fcd6-387b-4eea-8caa-df464ad24cf1/download](https://app.zenhub.com/files/293908949/0957fcd6-387b-4eea-8caa-df464ad24cf1/download)
