### ISSUE TITLE
Write Front-end code for the Landing page

### ISSUE THREAD

**Issue by manavsz** [UB-CSE/course-project-codeville#29]
-  Go to the page http://whoozeinit.herokuapp.com/ 
-  There should be a header and three frames below the header on the landing page.
-  The header should consist of a centre text having "WhoozinIt."
- The header should have a log in button.
- The header should have a Signup button.
-  Clicking on the login button on the header should take you to the Login page.
- Clicking on the SignUp button on the header should take you to the Signup page
-  The third frame of the landing page should have a button for Signup.
-  The third frame of the landing page should have a button for Contact us.
- Clicking on the SignUp on the third frame should take you to Signup page.
-  Clicking on the Contact us button should take you to the Contact us page.

**Comment by Manantiw** [comment]
[https://app.zenhub.com/files/293908949/b301ace6-d5fe-4e91-8706-afb5331c45c7/download](https://app.zenhub.com/files/293908949/b301ace6-d5fe-4e91-8706-afb5331c45c7/download)

**Comment by prakharpbuf** [comment]
def test_login_button(self):
        driver = self.driver
        button_exists = True
        try:
            button = driver.find_element_by_class_name("login").is_displayed()
        except NoSuchElementException:
            button_exists = False
        assert button_exists, "Login Button not displayed."

        button_click = True

        try:
            driver.find_element_by_class_name("login").click()
        except WebDriverException:
            button_click = False
        assert button_click, "Login Button not clickable."

 def test_signup_button(self):
        driver = self.driver
        button_exists = True
        try:
            button = driver.find_element_by_class_name("signup").is_displayed()
        except NoSuchElementException:
            button_exists = False
        assert button_exists, "SignUp Button not displayed."

        button_click = True

        try:
            driver.find_element_by_class_name("signup").click()
        except WebDriverException:
            button_click = False
        assert button_click, "Login Button not clickable."
